name: Swift Package Manager

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        swift build --sdk "$(xcrun --sdk iphonesimulator --show-sdk-path)" --triple arm64-apple-ios13.0-simulator
    - name: Build tests
      run: |
        swift build --build-tests --sdk "$(xcrun --sdk iphonesimulator --show-sdk-path)" --triple arm64-apple-ios13.0-simulator
