name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: xcodebuild test -workspace . -scheme Alerts-Package -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' -skipPackagePluginValidation -quiet
